Repository yugabyte/debezium-connector-yugabytedb, pull requests merged in 2023-07, with the labels that each got.

#242 Add commit_time from record to Kafka instead of response safe_time
  src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
  src/test/java/io/debezium/connector/yugabytedb/YugabyteDBColocatedTablesTest.java
  src/test/java/io/debezium/connector/yugabytedb/common/YugabyteDBContainerTestBase.java
Labels: bug

#243 Add task ID to the log statement while getting callback
  src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
  src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
Labels: enhancement

#244 Refactor wait code section into methods
  src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
  src/main/java/io/debezium/connector/yugabytedb/connection/OpId.java
Labels: enhancement

#246 Explicit checkpoint wait on Tablet Split is now based on LastRecordCheckpoint
  src/main/java/io/debezium/connector/yugabytedb/SourceInfo.java
  src/main/java/io/debezium/connector/yugabytedb/YugabyteDBOffsetContext.java
  src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
  src/main/java/io/debezium/connector/yugabytedb/connection/OpId.java
Labels: bug

#255 [yugabyte/yugabyte-db#18279] Retry logic for `GetCheckpoint` RPC
  src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
Labels: bug

#253 Unset time from children tablets upon initialization
  src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
  src/main/java/io/debezium/connector/yugabytedb/connection/OpId.java
Labels: bug, enhancement

#254 [yugabyte/yugabyte-db#18245] Use `lastRecordCheckpoint` to detect empty snapshot
  pom.xml
  src/main/java/io/debezium/connector/yugabytedb/SourceInfo.java
  src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
Labels: bug
